Repository MettyS/checkers, pull requests merged in 2021-03, with the labels that each got.

#7 Add basic starting hierarchy #4
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/README.md
  client/src/generated/.gitignore
  protobuf/README.md
  protobuf/todo.proto
  server/.gitignore
  server/README.md
  server/generated/.gitignore
  server/go.mod
  server/go.sum
  server/main.go
Labels: enhancement

#15 Add client linting
  client/.eslintrc.yaml
  client/package-lock.json
  client/package.json
  client/src/constants.js
  client/src/index.js
Labels: refactor

#16 Refactor client to vanilla MVC
  client/src/boardController.js
  client/src/boardModel.js
  client/src/boardView.js
  client/src/gameControlController.js
  client/src/gameControlModel.js
  client/src/gameControlView.js
  client/src/index.js
  client/src/util.js
Labels: refactor

#17 Translate to typescript
  client/.eslintrc.yaml
  client/dist/index.html
  client/package-lock.json
  client/package.json
  client/src/boardController.js
  client/src/boardController.ts
  client/src/boardModel.ts
  client/src/boardView.ts
  client/src/constants.ts
  client/src/gameControlController.ts
  client/src/gameControlModel.js
  client/src/gameControlModel.ts
  client/src/gameControlView.js
  client/src/gameControlView.ts
  client/src/generated/.gitignore
  client/src/index.ts
  client/src/util.ts
  client/tsconfig.json
  client/webpack.config.js
Labels: refactor

#18 Modify eslint configuration
  client/.eslintignore
  client/.eslintrc.yaml
  client/README.md
  client/tsconfig.eslint.json
  client/tsconfig.json
Labels: refactor

#20 Game controller handlers
  protobuf/game.proto
  protobuf/game_control.proto
  server/controller/central_checkers_controller.go
  server/domain/checkers.go
  server/gameplay/game_handler.go
  server/services/gamecontrol.go
  server/services/gameplay.go
Labels: enhancement, refactor

#23 Gameplay package initial tests.
  server/gameplay/game_hander_test.go
  server/gameplay/game_handler.go
Labels: tests

#24 Implement and stub unit tests
  client/package-lock.json
  client/package.json
  client/src/boardModel.ts
  client/src/boardUtil.ts
  client/src/boardView.ts
  client/src/gameControlController.ts
  client/src/gameController.ts
  client/src/gameService.ts
  client/src/gameServiceGrpc.ts
  client/src/index.ts
  client/test/boardModel.test.ts
Labels: enhancement

#25 Piece promotion, refactor, and documentation
  client/src/boardModel.ts
  client/src/boardUtil.ts
  client/src/boardView.ts
  client/test/boardModel.test.ts
Labels: documentation, enhancement, refactor, tests

#27 Add game logic and implement local game
  client/dist/index.html
  client/src/boardView.ts
  client/src/gameControlController.ts
  client/src/gameControlModel.ts
  client/src/gameControlModelLocal.ts
  client/src/gameControlModelRemote.ts
  client/src/gameControlView.ts
  client/src/gameController.ts
  client/src/index.ts
  client/test/boardModel.test.ts
  protobuf/game.proto
  protobuf/game_control.proto
  server/main.go
Labels: enhancement
